apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-grafana-loja
  namespace: flask-grafana
  labels:
    app: flask-grafana-loja
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: flask-grafana-loja
  template:
    metadata:
      labels:
        app: flask-grafana-loja
      annotations:
        # ---------------------------------------------------------
        # MUDANÇA 1: Comentamos o SigNoz (O "Pause" na injeção antiga)
        # instrumentation.opentelemetry.io/inject-python: "signoz/signoz-instrumentation"
        # ---------------------------------------------------------
    spec:
      containers:
        - name: flask-grafana-loja
          # ---------------------------------------------------------
          # MUDANÇA 2: Mantenha a imagem que o seu GitHub Actions vai substituir!
          # O script 'sed' vai procurar por "ghcr.io/amsatnaf/flask-grafana-loja:..." e trocar pelo SHA.
          # Pode deixar a última tag que estava lá, o robô vai atualizar sozinho.
          image: ghcr.io/amsatnaf/flask-grafana-loja:1706b7d50e238d531dd3ac0d4599337beb37b19f
          # ---------------------------------------------------------
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          # ---------------------------------------------------------
          # MUDANÇA 3: Variáveis de Ambiente para o GRAFANA ALLOY
          # ---------------------------------------------------------
          env:
          # Aponta para o serviço do Alloy (Agente) dentro do cluster
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://grafana-k8s-monitoring-alloy.monitoring.svc.cluster.local:4317"
          
          # Garante o protocolo gRPC (mais rápido)
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"

          # Nome do Serviço no Grafana Cloud
          - name: OTEL_SERVICE_NAME
            value: "flask-grafana-loja-loja"

          # --- Variáveis do Banco (Mantidas Iguais) ---
          - name: DB_HOST
            value: "34.44.72.27"
          - name: DB_NAME
            value: "loja_rum"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-gcp-creds
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-gcp-creds
                key: DB_PASS
