
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-web
  namespace: flask-prod
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: gce
  rules:
    - host: flask.prod.iptesteaqui.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-web
                port:
                  number: 80

