apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flask-prod

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - hpa.yaml
  - alert-config.yaml
  - alert-rules.yaml
