apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: flask-email-config
  # MUDANÇA IMPORTANTE: Vamos jogar direto no sistema
  namespace: cattle-monitoring-system
  labels:
    release: rancher-monitoring
spec:
  route:
    receiver: 'email-me'
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    matchers:
      - name: severity
        value: critical

  receivers:
  - name: 'email-me'
    emailConfigs:
    - to: 'diego.amsatnaf@l@gmail.com'
      from: 'diego.alme@hotmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'diego.amsatnaf@l@gmail.com'
      authIdentity: 'sdiego.amsatnaf@l@gmail.com'
      authPassword:
        name: email-auth # Agora ele vai achar, pois ambos estão no cattle-monitoring-system
        key: password
      requireTLS: true
