name: CI - Testes Automatizados

# Roda em qualquer branch (para você saber se quebrou algo enquanto programa)
on: [push, pull_request]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          #pip install flask pytest flake8 prometheus-flask-exporter
          pip install -r app/requirements.txt

      # Verifica se tem erro de sintaxe (como aquele "200 - texto" que tivemos)
      - name: Verificar Sintaxe (Linting)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Roda o teste de verdade
      - name: Rodar Testes
        run: |
          # O python adiciona a pasta atual ao path para achar o seu "app"
          export PYTHONPATH=$PYTHONPATH:.
          pytest
